# Generated by Django 5.2.6 on 2025-09-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepimage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analyst_id', models.CharField(default='System Auto-Detection', max_length=100)),
                ('media_source', models.CharField(default='File Upload', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video_frame', 'Video Frame'), ('screenshot', 'Screenshot')], default='image', max_length=50)),
                ('original_file', models.ImageField(upload_to='forensic_uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('file_hash_md5', models.CharField(blank=True, max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('metadata_inconsistencies', models.TextField(blank=True)),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('likely_genuine', 'Likely Genuine'), ('suspected_fake', 'Suspected Fake'), ('confirmed_fake', 'Confirmed Fake')], default='likely_genuine', max_length=50)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('detected_artifacts', models.JSONField(blank=True, default=list)),
                ('heatmap_path', models.CharField(blank=True, max_length=255)),
                ('model_ensemble_results', models.JSONField(blank=True, default=dict)),
                ('adversarial_detection', models.JSONField(blank=True, default=dict)),
                ('detected_toolkit', models.CharField(blank=True, max_length=100)),
                ('cross_correlation', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('recommended_action', models.CharField(choices=[('flag_review', 'Flag for Human Review'), ('archive', 'Archive as Verified Deepfake'), ('alert_units', 'Alert Counter-Disinformation Units'), ('correlate', 'Correlate with Investigations')], default='flag_review', max_length=100)),
                ('raw_prediction_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('facial_asymmetry', 'Facial Asymmetry'), ('lighting_inconsistency', 'Lighting/Shadow Inconsistencies'), ('skin_texture', 'Skin Texture Anomalies'), ('eye_reflection', 'Eye Reflection Anomalies'), ('background_mismatch', 'Background Mismatch'), ('blink_pattern', 'Blink Pattern Anomalies'), ('color_inconsistency', 'Color Inconsistency')], max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepimage.forensicanalysis')),
            ],
        ),
    ]
